<h2>Add Holidays</h2>

<form action='/admin/editholidays' method="post">

    <p>
        <label>Add new day as Holidays (format: 2001-01-01)</label>
        <input type="text" name="holiday" placeholder="2001-01-01">
    </p>

    <p>
        <label>Repeat</label>
        <input type="checkbox" name="isRepeated" value="Repeat">
    </p>

    <p>
        <input type='submit' value='Add' />
    </p>

</form>