<h2>Edit staff hours</h2>

<form action='/admin/staffhoursedit' method="post">

    <?php foreach ($data['staffHours'] as $index => $staffHours) {

        echo '<div class="staff_hours_child_' . $index . '">';?>
    <div id="staff_hours">

        <label>Start <?php echo ($index+1).': '. strftime("%a %d %b, %Y", strtotime($staffHours['start_time']))?></label>
        <input type="text" name=start+"<?php echo $index?>" value="<?php echo $staffHours['start_time']?>">
    </div>

    <p>
        <label>Stop <?php echo ($index+1).': '. strftime("%a %d %b, %Y", strtotime($staffHours['stop_time']))?></label>
        <input type="text" name="<?php echo 'stop'.$index?>" value="<?php echo $staffHours['stop_time']?>">
    </p>

    <?php } ?>

    <input style="display: none" name="id" value="<?php echo $user->id?>">
    <input style="display: none" name="day" value="<?php echo $day?>">
    <input style="display: none" name="month" value="<?php echo $month?>">
    <input style="display: none" name="year" value="<?php echo $year?>">

    <p>
        <input type='submit' value='Update' />
    </p>

</form>