<!DOCTYPE html>
<html>
<style>
    table, th, td {
        margin: 30px;
        border:1px solid black;
        padding: 5px;
    }
</style>
<body>
    <table>
        <tr>
            <th>Name Surname</th>
            <th>Login</th>
            <th>Email</th>
<!--            <th>Password</th>-->
            <th>Arrived Time for today</th>
            <th></th>
            <th></th>
        </tr>
        <?php
        $workhour_start = $users[0]->workhour_start;
        foreach ($users as $index => $user) {?>
        <tr>
            <td><a href="/admin/staffmonth/<?php echo $user->id; ?>"><?php echo $user->fullName; ?></a></td>
            <td><?php echo $user->login; ?></td>
            <td><?php echo $user->email; ?></td>
<!--            <td>--><?php //echo $user->password; ?><!--</td>-->
            <?php
            $workhour = strftime("%H:%M:%S", strtotime($workhour_start));
            $hour = date('Y-m-d '.$workhour);
                if($userArrivedTimes[$index] == NULL) { ?>
                <td><?php echo strftime("%H:%M:%S", strtotime($userArrivedTimes[$index])); ?></td>
            <?php } else if($userArrivedTimes[$index] < $hour) {?>
                <td style="background-color: lightgreen"><?php echo strftime("%H:%M:%S", strtotime($userArrivedTimes[$index])); ?></td>
            <?php } else {?>
                <td style="background-color: #FF6666"><?php echo strftime("%H:%M:%S", strtotime($userArrivedTimes[$index])); ?></td>
            <?php } ?>
            <td><a href="/admin/useredit/<?php echo $user->id; ?>">Edit</a></td>
            <td><a href="/admin/userdelete/<?php echo $user->id; ?>">Delete</a></td>
        </tr>
        <?php } ?>
    </table>

    <p><a href="/admin/showlatecomers/">Show list of late comers</a></p>
    <p><a href="/admin/useradd/">Add new user</a></p>
    <p><a href="/admin/addholidays">Add Non-working days</a></p>
    <p><a href="/mainpage">Go to Profile Page</a></p>
</body>