<style>
    table, th, td {
        margin: 30px;
        border:1px solid black;
        padding: 5px;
    }
</style>
<body>
    <h4>List of Late Comers</h4>
    <p><a href="/admin">Go back to Admin Panel</a></p>
    <p><a href="/admin/changeworkhour">Change Begining of working day</a></p>

    <p style="font-weight: bold">Begining of working day: <?php echo strftime("%H:%M", strtotime($users[0]->workhour_start)) ?></p>
    <table>
        <tr>
            <th>Name Surname</th>
            <th>Login</th>
            <th>Arrived Time</th>
        </tr>
        <?php
        if(count($users) != 0) {
            $workhour_start = $users[0]->workhour_start;
            for ($user_i = 0; $user_i < count($users); $user_i++) {
                if(count($userArrivedTimes[$user_i]) != 0)
                for ($sh_i = 0; $sh_i < count($userArrivedTimes[$user_i]); $sh_i++) {
                    $hour = strftime("%H:%M:%S", strtotime($workhour_start));
                    $arrivedTime = strftime("%H:%M:%S", strtotime($userArrivedTimes[$user_i][$sh_i]['start_time']));
                    if($arrivedTime > $hour and $userArrivedTimes[$user_i][$sh_i]['start_time'] != NULL) {
                    ?>
                    <tr>
                        <td><a href="/admin/staffmonth/<?php echo $users[$user_i]->id; ?>"><?php echo $users[$user_i]->fullName; ?></a></td>
                        <td><?php echo $users[$user_i]->login; ?></td>
                        <td><?php echo $userArrivedTimes[$user_i][$sh_i]['start_time'] ?></td>
                    </tr>
                <?php
                    }
                }
            }
        }?>
    </table>

</body>