<h2>Add new user</h2>

<form action='/admin/usernew' method="post">

    <p>
        <label>Name Surname</label>
        <input type="text" name="fullName" placeholder="Type your full name">
    </p>

    <p>
        <label>Login</label>
        <input type="text" name="login" placeholder="Type your login">

    </p>
    <p>
        <label>Email</label>
        <input type="email" name="email" placeholder="Type your email">
    </p>
    <p>
        <label>Password</label>
        <input type="password" name="password" placeholder="Type your password">
    </p>

    <p>
        <input type='submit' value='Add' />
    </p>

</form>