<html>
<style>
    table, th, td {
        margin: 30px;
        border:1px solid black;
        padding: 5px;
    }
</style>
    <body>
    <h4>Welcome to Time Tracking, <?php echo $this->session->get('AUTH_NAME')?></h4>

    <?php if(strcmp($this->session->get('AUTH_LOGIN'), 'admin') == 0) {?>
        <p><a href="/admin">Go to Admin Panel</a></p>
    <?php } ?>

    <a href="/logout">
        <input type="button" value="Logout" />
    </a>

    <p><a href="/changepassword">Change password</a></p>

    <h5>В этом месяце, ты отработал <?php echo $doneMonthStaff ?> часов из необходимых <?php echo $monthStaffHours ?> часов</h5>

    <input style="display: none" id="user_id" value="<?php echo $this->session->get('AUTH_ID')?>">

    <table>
        <tr>
            <th>Today</th>
            <th>Start/Stop</th>
            <th> Staff
                <select name="months" id="months">
                    <option value="1">January</option>
                    <option value="2">February</option>
                    <option value="3">March</option>
                    <option value="4">April</option>
                    <option value="5">May</option>
                    <option value="6">June</option>
                    <option value="7">July</option>
                    <option value="8">August</option>
                    <option value="9">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
            </th>
        </tr>

<!--        <button id="hide">Hide</button>-->
<!--        <button id="show">Show</button>-->
        <?php
        $monthDays = cal_days_in_month(CAL_GREGORIAN, $currentMonth, $currentYear);
        $isStart = false;
        for ($i = 1; $i <= $monthDays; $i++) { ?>
        <tr>
            <td>
                <?php echo strftime("%a %d %b, %Y", strtotime($i.'-'.$currentMonth.'-'.$currentYear));
                $day = strtotime($currentYear.'-'.$currentMonth.'-'.$i);
                $dayofweek = date('w', $day);
                $holiday_day = strtotime($currentYear.'-'.$currentMonth.'-'.$i.' 00:00:00');
                if($dayofweek == 0 || $dayofweek == 6 || in_array($holiday_day, $holidays)) {?>
                    <input type="checkbox" disabled >
                <?php }
                else {?>
                    <input type="checkbox" checked disabled>
                <?php } ?>
            </td>
                <td>
                    <div
                        <?php
                        if (strftime("%d %b %Y", strtotime($i . '-' . $currentMonth . '-' . $currentYear)) == strftime("%d %b %Y", time())) {
                            echo "id = 'today'";
                        }
                        ?>
                        >
                        <div id="staff_hours">
                            <?php
                            if(strftime("%d %b %Y", strtotime($i.'-'.$currentMonth.'-'.$currentYear))==strftime("%d %b %Y", time())) {
                                $isStart = true;?>
                                <input style="display: none" id="today" value="<?php echo $i?>">
                                <input style="display: none" id="month" value="<?php echo $currentMonth?>">
                                <input style="display: none" id="year" value="<?php echo $currentYear?>">
                            <?php
                            }
                            foreach ($data['staffHours'] as $index => $staffHours) {
                                if(strftime("%d %b %Y", strtotime($staffHours['start_time'])) == strftime("%d %b %Y", strtotime($i.'-'.$currentMonth.'-'.$currentYear))) {
                                    echo '<div class="staff_hours_child_' . $index . '">';
                                    echo '<div class="start_' . $index . '">';
                                    echo strftime("%H:%M:%S", strtotime($staffHours['start_time']));
                                    echo '-</div>';
                                    if($staffHours['stop_time']) {
                                        echo '<div class="stop_' . $index . '">' . strftime("%H:%M:%S", strtotime($staffHours['stop_time']));
                                        echo '</div>';
                                    }
                                    echo '</div><br>';
                                }
                            } ?>
                        </div>
                        <div>
                            <?php if($isStart) {
                                if($data['stopButtonActive']) {?>
                                    <button id="start_stop" value="stop">Stop</button>
                                    <?php
                                } else { ?>
                                    <button id="start_stop" value="start">Start</button>
                                <?php }
                                    $isStart = false;
                            } ?>
                        </div>
                    </div>
                </td>
                <td>
                    <div
                        <?php
                        if (strftime("%d %b %Y", strtotime($i . '-' . $currentMonth . '-' . $currentYear)) == strftime("%d %b %Y", time())) {
                            echo "id = 'today_int'";
                        }
                        ?>
                    >
                    <?php echo gmdate("H:i:s", $intervals[$i-1]); ?>
                    </div>
                </td>
        </tr>
            <?php
        }
        ?>

    </table>


    <script type="text/javascript" src="js/jquery.min.js"></script>
        <script>
            let choosedMonth = '<?php echo $currentMonth ?>'
            $('#months').val("" + choosedMonth).change()

            $('select').on('change', function() {

                console.log('/mainpage?month='+$('#months').val()+'&year=2021');
                window.location.href = '/mainpage?month='+$('#months').val()+'&year=2021';
            });

            // $('#hide').click(function () {
            //     $('tr').not('#today').hide();
            // })
            // $('#show').click(function () {
            //     $('tr').show();
            // })

            $('#start_stop').click(function () {
                let buttonValue = $('#start_stop').val();
                if (buttonValue === 'start') {
                    $('#start_stop').val('stop')
                    $('#start_stop').html('Stop')

                    startClicked()
                } else {
                    $('#start_stop').val('start')
                    $('#start_stop').html('Start')

                    stopClicked()
                }
            })

            function startClicked() {

                let userId = $('input[id="user_id"]').val();

                var request = new XMLHttpRequest();
                request.open("POST", '/start', true);

                request.setRequestHeader("content-type", "application/x-www-form-urlencoded");

                request.onreadystatechange = function() {
                    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {

                        var response = JSON.parse(request.response)
                        if(response.success) {
                            let nextChildCount = $('#staff_hours>div').length + 1
                            $('#today>#staff_hours').append('<div class="staff_hours_child_'+nextChildCount+'">' +
                                '<div class="start_'+nextChildCount+'">' +  response.start_time + '-</div>' +
                             '<div class="stop_'+nextChildCount+'"></div></div>')
                        }
                    }
                }
                request.send("userId="+userId+"");
            }

            function stopClicked() {

                let userId = $('input[id="user_id"]').val();
                let day = $('input[id="today"]').val();
                let month = $('input[id="month"]').val();
                let year = $('input[id="year"]').val();
                let stopDivIndex = $('#stop').val();

                var request = new XMLHttpRequest();
                request.open("POST", '/stop', true);

                request.setRequestHeader("content-type", "application/x-www-form-urlencoded");

                request.onreadystatechange = function() {
                    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
                        var response = JSON.parse(request.response)
                        if(response.success) {
                            $('#today_int').html(response.interval)
                            $('.stop_'+stopDivIndex).html(response.stop_time)
                            let nextChildCount = $('#staff_hours>div').length + 1
                            $('#today>#staff_hours').append('<div class="staff_hours_child_'+nextChildCount+'">' +
                                '<div class="stop_'+nextChildCount+'">' + response.stop_time + '</div></div><br>')
                        }
                    }
                }

                request.send("userId="+userId+"&day="+day+"&month="+month+"&year="+year);
            }
        </script>
    </body>
</html>