<html>
<style>
    table, th, td {
        margin: 30px;
        border:1px solid black;
        padding: 5px;
    }
</style>
    <body>
    <h4>Welcome to Time Tracking, <?php echo $this->session->get('AUTH_NAME')?></h4>

    <p><a href="/admin">Go to Admin Panel</a></p>

    <a href="/logout">
        <input type="button" value="Logout" />
    </a>

    <p><a href="/changepassword">Change password</a></p>

    <input style="display: none" id="user_id" value="<?php echo $this->session->get('AUTH_ID')?>">

    <table style="border:solid 1px ">
        <tr style="border: solid 1px">
            <th>Today</th>
            <th>Start/Stop</th>
            <th>Staff</th>
        </tr>
        <tr>
            <td><?php echo date('d-M-Y', time()) ?></td>

            <td>
                <div style="display: flex">
                    <div id="staff_hours"><?php foreach ($data['staffHours'] as $index => $staffHours) {
                            echo '<div class="staff_hours_child_' . $index . '">';
                            echo '<div class="start_' . $index.'">';
                            echo $staffHours['start_time'];
                            echo '-</div>'; echo '<div class="stop_' . $index . '">' . $staffHours['stop_time']   ?? "";
                            echo '</div>';
                            echo '</div><br>';
                        } ?>
                    </div>
                    <div>
                        <button id="start_stop" value="start">Start</button>
                    </div>
                </div>

            </td>
            <td>
                staff hours
            </td>
        </tr>

    </table>


    <script type="text/javascript" src="js/jquery.min.js"></script>
        <script>

            $('#start_stop').click(function () {
                let buttonValue = $('#start_stop').val();
                if (buttonValue === 'start') {
                    $('#start_stop').val('stop')
                    $('#start_stop').html('Stop')

                    startClicked()
                } else {
                    $('#start_stop').val('start')
                    $('#start_stop').html('Start')

                    stopClicked()
                }
            })

            function startClicked() {

                let userId = $('input[id="user_id"]').val();

                var request = new XMLHttpRequest();
                request.open("POST", '/start', true);

                request.setRequestHeader("content-type", "application/x-www-form-urlencoded");

                request.onreadystatechange = function() {
                    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {

                        var response = JSON.parse(request.response)
                        if(response.success) {
                            let nextChildCount = $('#staff_hours>div').length + 1
                            $('#staff_hours').append('<div class="staff_hours_child_'+nextChildCount+'">' +
                                '<div class="start_'+nextChildCount+'">' + response.start_time + '-</div>' +
                             '<div class="stop_'+nextChildCount+'"></div></div>')
                        }
                    }
                }
                request.send("userId="+userId+"");
            }

            function stopClicked() {

                let userId = $('input[id="user_id"]').val();
                let stopDivIndex = $('#stop').val();

                var request = new XMLHttpRequest();
                request.open("POST", '/stop', true);

                request.setRequestHeader("content-type", "application/x-www-form-urlencoded");

                request.onreadystatechange = function() {
                    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
                        var response = JSON.parse(request.response)
                        if(response.success) {
                            $('.stop_'+stopDivIndex).html(response.stop_time)
                            let nextChildCount = $('#staff_hours>div').length + 1
                            $('#staff_hours').append('<div class="staff_hours_child_'+nextChildCount+'">' +
                                '<div class="stop_'+nextChildCount+'">' + response.stop_time + '</div></div><br>')
                        }
                    }
                }

                request.send("userId="+userId);
            }
        </script>
    </body>
</html>