<form action="/user/changepassword" method="post">
    <p>
        <label>Password</label>
        <input type="password" name="password1">
    </p>
    <p>
        <label>Repeat Password</label>
        <input type="password" name="password2">
    </p>

    <input style="display: none" name="id" value="<?php echo $this->session->get('AUTH_ID')?>">

    <p>
        <input type='submit' value='Change Password' />
    </p>

</form>